/**
 * Image forensics — detects AI-generated and manipulated images.
 *
 * Strategy:
 *   1. Send the image to a trained AI detection model (ViT neural network)
 *      via our server-side API → HuggingFace free Inference API.
 *      This is the primary signal — same tech the real detection companies use.
 *   2. Extract EXIF metadata (camera, software, GPS, dates) client-side.
 *   3. Combine both into a clear verdict with explanation.
 *
 * The AI model is always the dominant signal. Metadata is supporting evidence.
 * If the API call fails, we fall back to metadata-only analysis.
 */

export interface ForensicFinding {
  text: string;
  type: 'good' | 'bad' | 'neutral';
}

export interface ForensicReport {
  verdict: 'ai' | 'real' | 'uncertain';
  verdict_label: string;
  confidence: number;
  explanation: string;
  findings: ForensicFinding[];
  ai_score: number | null;
  metadata: {
    camera: string | null;
    software: string | null;
    date: string | null;
    has_gps: boolean;
    has_exif: boolean;
  };
}

export async function analyzeImage(file: File): Promise<ForensicReport> {
  // Run AI model detection and metadata extraction in parallel
  const [modelResult, metadata] = await Promise.all([
    detectWithAiModel(file),
    extractMetadata(file),
  ]);

  const findings: ForensicFinding[] = [];
  let verdict: 'ai' | 'real' | 'uncertain' = 'uncertain';
  let confidence = 0;
  let explanation = '';
  let aiScore: number | null = null;

  // ── AI MODEL RESULT (primary signal) ────────────────────────────────
  if (modelResult.ok && modelResult.ai_score !== null) {
    aiScore = modelResult.ai_score;
    const pct = Math.round(modelResult.ai_score * 100);
    const humanPct = Math.round(modelResult.human_score * 100);

    if (modelResult.ai_score > 0.70) {
      verdict = 'ai';
      confidence = pct;
      explanation = `Our AI detection model is ${pct}% confident this image was generated by AI — not captured by a camera. The model is a neural network trained on millions of real and AI-generated images, and it detected patterns characteristic of AI generators like DALL-E, Midjourney, and Stable Diffusion.`;
      findings.push({ text: `AI detection model: ${pct}% AI-generated`, type: 'bad' });
    } else if (modelResult.ai_score > 0.50) {
      verdict = 'ai';
      confidence = pct;
      explanation = `Our AI detection model gives this a ${pct}% probability of being AI-generated. The image has characteristics the model associates with synthetic content rather than real photography.`;
      findings.push({ text: `AI detection model: ${pct}% likely AI`, type: 'bad' });
    } else if (modelResult.human_score > 0.70) {
      verdict = 'real';
      confidence = humanPct;
      explanation = `Our AI detection model is ${humanPct}% confident this is a real photograph — not AI-generated. The image has the characteristics of genuine camera-captured content.`;
      findings.push({ text: `AI detection model: ${humanPct}% real photo`, type: 'good' });
    } else if (modelResult.human_score > 0.50) {
      verdict = 'real';
      confidence = humanPct;
      explanation = `Our AI detection model gives this a ${humanPct}% probability of being a real photograph. It leans toward authentic but isn't highly confident.`;
      findings.push({ text: `AI detection model: ${humanPct}% likely real`, type: 'good' });
    } else {
      confidence = 50;
      explanation = `Our AI detection model couldn't clearly determine if this is AI-generated (${pct}%) or real (${humanPct}%). The image has mixed characteristics.`;
      findings.push({ text: `AI detection model: ${pct}% AI / ${humanPct}% real — too close to call`, type: 'neutral' });
    }
  } else {
    // Model failed — note it but continue with metadata
    if (modelResult.error) {
      findings.push({ text: 'AI model analysis unavailable — using metadata only', type: 'neutral' });
    }
  }

  // ── METADATA (supporting evidence) ──────────────────────────────────
  if (metadata.camera) {
    findings.push({ text: `Camera: ${metadata.camera}. Real photos carry camera data; AI images don't.`, type: 'good' });
    if (verdict === 'uncertain') { verdict = 'real'; confidence = Math.max(confidence, 65); }
  } else if (metadata.has_exif) {
    findings.push({ text: 'Has some metadata but no camera make/model — could be a screenshot or processed image.', type: 'neutral' });
  } else {
    findings.push({ text: 'No metadata at all. Real camera photos almost always have EXIF data.', type: 'bad' });
    if (verdict === 'uncertain') { verdict = 'ai'; confidence = Math.max(confidence, 55); }
  }

  if (metadata.software) {
    const sw = metadata.software.toLowerCase();
    const aiTools = ['dall-e', 'openai', 'midjourney', 'stable diffusion', 'firefly', 'imagen', 'comfyui'];
    const isAiTool = aiTools.some(t => sw.includes(t));
    if (isAiTool) {
      findings.push({ text: `Created with AI tool: "${metadata.software}"`, type: 'bad' });
      verdict = 'ai';
      confidence = Math.max(confidence, 95);
      explanation = `This image was created using "${metadata.software}" — an AI image generation tool. This is confirmed by the metadata embedded in the file.`;
    } else {
      findings.push({ text: `Edited with: ${metadata.software}`, type: 'neutral' });
    }
  }

  if (metadata.has_gps) {
    findings.push({ text: 'GPS location embedded — social media and AI tools strip this. Strong sign of original camera photo.', type: 'good' });
    if (verdict !== 'ai' || confidence < 60) { verdict = 'real'; confidence = Math.max(confidence, 75); }
  }

  if (metadata.date) {
    findings.push({ text: `Timestamp: ${metadata.date}`, type: 'neutral' });
  }

  // ── FINAL VERDICT ───────────────────────────────────────────────────
  if (!explanation) {
    if (verdict === 'ai') {
      explanation = `Based on the available evidence, this image is likely AI-generated. ${!metadata.camera ? 'It has no camera metadata, which is unusual for real photos.' : ''}`;
    } else if (verdict === 'real') {
      explanation = `Based on the available evidence, this appears to be a real photograph. ${metadata.camera ? `It was taken with a ${metadata.camera}.` : ''}`;
    } else {
      explanation = 'We couldn\'t determine with confidence whether this is AI-generated or real. The evidence is mixed.';
    }
  }

  const verdict_label =
    verdict === 'ai' ? (confidence >= 70 ? 'AI-generated image' : 'Probably AI-generated')
    : verdict === 'real' ? (confidence >= 70 ? 'Real photograph' : 'Probably a real photo')
    : 'Uncertain';

  return {
    verdict,
    verdict_label,
    confidence,
    explanation,
    findings,
    ai_score: aiScore,
    metadata,
  };
}

// ── AI MODEL DETECTION ──────────────────────────────────────────────────

interface ModelResult {
  ok: boolean;
  ai_score: number;
  human_score: number;
  error: string | null;
}

async function detectWithAiModel(file: File): Promise<ModelResult> {
  try {
    // Convert file to base64 for the JSON API
    const buffer = await file.arrayBuffer();
    const base64 = bufferToBase64(new Uint8Array(buffer));

    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 35_000);

    const res = await fetch('/api/image-forensics', {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ image_base64: base64 }),
      signal: ctrl.signal,
    });
    clearTimeout(timer);

    if (!res.ok) {
      const text = await res.text().catch(() => '');
      return { ok: false, ai_score: 0, human_score: 0, error: `${res.status}: ${text.slice(0, 100)}` };
    }

    const data = await res.json();
    if (!data.ok) {
      return { ok: false, ai_score: 0, human_score: 0, error: data.error ?? 'model failed' };
    }

    // Parse HuggingFace labels
    const labels = data.labels as Array<{ label: string; score: number }>;
    let aiScore = 0;
    let humanScore = 0;

    for (const l of labels) {
      const name = l.label.toLowerCase();
      if (name.includes('artificial') || name.includes('ai') || name.includes('fake') || name.includes('generated')) {
        aiScore = Math.max(aiScore, l.score);
      }
      if (name.includes('human') || name.includes('real') || name.includes('natural') || name.includes('authentic')) {
        humanScore = Math.max(humanScore, l.score);
      }
    }

    return { ok: true, ai_score: aiScore, human_score: humanScore, error: null };
  } catch (err) {
    return {
      ok: false,
      ai_score: 0,
      human_score: 0,
      error: err instanceof Error ? err.message : 'failed',
    };
  }
}

function bufferToBase64(bytes: Uint8Array): string {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]!);
  }
  return btoa(binary);
}

// ── METADATA EXTRACTION ─────────────────────────────────────────────────

async function extractMetadata(file: File): Promise<ForensicReport['metadata']> {
  const result = {
    camera: null as string | null,
    software: null as string | null,
    date: null as string | null,
    has_gps: false,
    has_exif: false,
  };

  try {
    const exifr = await import('exifr');
    const data = await exifr.default.parse(file, true);
    if (!data) return result;

    result.has_exif = true;

    if (data.Make && data.Model) {
      result.camera = `${data.Make} ${data.Model}`.trim();
    } else if (data.Make) {
      result.camera = data.Make;
    } else if (data.Model) {
      result.camera = data.Model;
    }

    result.software = data.Software ?? data.Creator ?? data.CreatorTool ?? null;

    if (data.DateTimeOriginal) {
      result.date = data.DateTimeOriginal instanceof Date
        ? data.DateTimeOriginal.toLocaleDateString() + ' ' + data.DateTimeOriginal.toLocaleTimeString()
        : String(data.DateTimeOriginal);
    }

    if (data.latitude != null && data.longitude != null) {
      result.has_gps = true;
    }
  } catch {
    // No parseable metadata
  }

  return result;
}
